IGNORE_DIRS = {
    ".git",
    "node_modules",
    "venv",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".tox",
    "dist",
    "build",
    ".next",
    "out",
    ".idea",
    ".vscode",
    "htmlcov",
    ".eggs",
    "site-packages",
}

IGNORE_EXTENSIONS = {
    ".pyc",
    ".pyo",
    ".pyd",
    ".so",
    ".dll",
    ".dylib",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".ico",
    ".webp",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".7z",
    ".rar",
    ".exe",
    ".bin",
    ".pkl",
    ".pickle",
    ".mp4",
    ".mp3",
    ".wav",
    ".pdf",
}

HIGH_PRIORITY_NAMES = {
    "requirements.txt",
    "requirements-dev.txt",
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "cmakelists.txt",
    "makefile",
    "environment.yml",
    "environment.yaml",
    "conda.yaml",
    "conda.yml",
    "pipfile",
    "pipfile.lock",
    "cargo.toml",
    "go.mod",
}

HIGH_PRIORITY_BASENAMES = {
    "dockerfile",
    "makefile",
    "cmakelists.txt",
}

HIGH_PRIORITY_EXTENSIONS = {
    ".cu",
    ".cuh",
    ".cmake",
    ".hip",
}
