"use client";

import type { AnalyzeResponse } from "@/types/analysis";
import { downloadBenchmarkScript } from "@/lib/api";

interface Props {
  analysis: AnalyzeResponse;
}

export function DeployTab({ analysis }: Props) {
  const steps = analysis.artifacts?.deployGuide ?? [];

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold">
        Deployment Guide
      </h2>

      <button
        onClick={downloadBenchmarkScript}
        className="rounded-lg bg-red-600 px-4 py-2 text-white transition hover:bg-red-500"
      >
        Download Benchmark Script
      </button>

      <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-5">
        <h3 className="text-lg font-semibold">
          ROCm Benchmark Script
        </h3>

        <p className="mt-2 text-sm text-zinc-400">
          Downloads a ready-to-run ROCm benchmark script for AMD GPU systems.
          The script:
        </p>

        <ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-zinc-300">
          <li>Checks the Docker installation</li>
          <li>Pulls the latest ROCm PyTorch image</li>
          <li>Starts a ROCm-enabled container</li>
          <li>Runs <code>benchmark.py</code></li>
          <li>Prints benchmark execution logs</li>
        </ul>

        <p className="mt-4 text-xs text-yellow-400">
          No benchmark numbers are generated by AMD Port Studio.
          Execute this script on an AMD ROCm machine to obtain real measurements.
        </p>
      </div>

      {steps.map((step, index) => (
        <div
          key={index}
          className="rounded-xl border border-zinc-800 bg-zinc-900 p-6 transition-all duration-200 hover:border-red-500 hover:shadow-lg hover:shadow-red-500/10"
        >
          <div className="mb-2 text-sm text-zinc-500">
            Step {index + 1}
          </div>

          <div>{step}</div>
        </div>
      ))}
    </div>
  );
}