from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from typing import Any

# ---------------------------------------------------------
# Styles
# ---------------------------------------------------------

styles = getSampleStyleSheet()

TITLE = ParagraphStyle(
    "AMDTitle",
    parent=styles["Title"],
    alignment=TA_CENTER,
    fontSize=28,
    textColor=colors.HexColor("#C8102E"),
    spaceAfter=16,
)

SUBTITLE = ParagraphStyle(
    "AMDSubtitle",
    parent=styles["Heading2"],
    alignment=TA_CENTER,
    textColor=colors.HexColor("#666666"),
    spaceAfter=30,
)

SECTION = ParagraphStyle(
    "AMDSection",
    parent=styles["Heading2"],
    textColor=colors.HexColor("#C8102E"),
    spaceAfter=10,
)

BODY = ParagraphStyle(
    "AMDBody",
    parent=styles["BodyText"],
    leading=18,
)

SMALL = ParagraphStyle(
    "Small",
    parent=styles["BodyText"],
    fontSize=9,
    textColor=colors.grey,
)

# ---------------------------------------------------------
# Helpers
# ---------------------------------------------------------


def hr(story):
    line = Table(
        [[""]],
        colWidths=[7.2 * inch],
    )

    line.setStyle(
        TableStyle(
            [
                (
                    "LINEBELOW",
                    (0, 0),
                    (-1, -1),
                    1,
                    colors.HexColor("#DDDDDD"),
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
            ]
        )
    )

    story.append(line)
    story.append(Spacer(1, 18))


def page_template(canvas, doc):

    canvas.saveState()

    #
    # Header
    #

    canvas.setFont(
        "Helvetica-Bold",
        10,
    )

    canvas.setFillColor(
        colors.HexColor("#C8102E"),
    )

    canvas.drawString(
        36,
        810,
        "AMD Port Studio",
    )

    canvas.setFillColor(colors.black)

    canvas.setFont(
        "Helvetica",
        9,
    )

    repo = getattr(
        doc,
        "repository_name",
        "",
    )

    canvas.drawRightString(
        560,
        810,
        repo,
    )

    canvas.setStrokeColor(
        colors.HexColor("#DDDDDD"),
    )

    canvas.line(
        36,
        800,
        560,
        800,
    )

    #
    # Footer
    #

    canvas.setFillColor(colors.grey)

    canvas.setFont(
        "Helvetica",
        8,
    )

    canvas.drawString(
        36,
        20,
        "Generated by AMD Port Studio",
    )

    canvas.drawRightString(
        560,
        20,
        datetime.now().strftime("%d %b %Y")
        + f" | Page {doc.page}",
    )

    canvas.restoreState()


# ---------------------------------------------------------
# PDF
# ---------------------------------------------------------


def generate_pdf(
    analysis: dict,
):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=36,
        leftMargin=36,
        topMargin=40,
        bottomMargin=40,
    )

    repository = analysis.get(
        "repository",
        {},
    )

    findings = analysis.get(
        "findings",
        {},
    )

    compatibility = findings.get(
        "compatibility",
        {},
    )

    advisor = findings.get(
        "aiAdvisor",
        {},
    )

    confidence = analysis.get(
        "confidence",
        {},
    )

    recommendations = analysis.get(
        "recommendations",
        [],
    )

    metrics = analysis.get(
        "metrics",
        {},
    )

    setattr(
    doc,
    "repository_name",
    repository.get(
        "name",
        "",
        ),
    )

    story = []

    # =====================================================
    # COVER PAGE
    # =====================================================

    story.append(
        Spacer(
            1,
            0.4 * inch,
        )
    )

    story.append(
        Paragraph(
            "AMD PORT STUDIO",
            TITLE,
        )
    )

    story.append(
        Paragraph(
            "AI Migration Assessment Report",
            SUBTITLE,
        )
    )

    story.append(
        Spacer(
            1,
            0.35 * inch,
        )
    )

    story.append(
        Paragraph(
            "<b>Repository</b>",
            SECTION,
        )
    )

    story.append(
        Paragraph(
            repository.get(
                "name",
                "Unknown Repository",
            ),
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            10,
        )
    )

    story.append(
        Paragraph(
            f"<b>Repository URL:</b> {repository.get('url','-')}",
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            10,
        )
    )

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now().strftime('%d %B %Y %H:%M')}",
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            22,
        )
    )

    story.append(
        Paragraph(
            """
            This report was automatically generated by
            <b>AMD Port Studio</b>.

            The assessment combines deterministic repository
            scanning, compatibility analysis, dependency graph
            generation, AI-assisted migration planning,
            and ROCm best-practice recommendations.
            """,
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            32,
        )
    )

    hr(story)

    story.append(
        Paragraph(
            """
            <font color="#777777">

            This report is intended to accelerate
            migration from NVIDIA CUDA to AMD ROCm
            by providing repository-specific
            migration guidance.

            </font>
            """,
            SMALL,
        )
    )

    story.append(
        Spacer(
            1,
            24,
        )
    )

    # =====================================================
    # PART 2 STARTS HERE
    # =====================================================

        # =====================================================
    # Repository Summary
    # =====================================================

    languages = repository.get("languages", {})

    language_names = list(languages.keys())[:5]

    language_text = ", ".join(language_names)

    if len(languages) > 5:
        language_text += " ..."

    score = compatibility.get(
        "score",
        "-",
    )

    migration_complexity = advisor.get(
        "migrationComplexity",
        compatibility.get(
            "migrationComplexity",
            compatibility.get(
                "complexity",
                "-",
            ),
        ),
    )

    estimated_hours = advisor.get(
        "estimatedHours",
        "-",
    )

    risk_level = advisor.get(
        "riskLevel",
        "-",
    )

    story.append(
        Paragraph(
            "Repository Summary",
            SECTION,
        )
    )

    summary = [
        [
            "Repository",
            repository.get(
                "name",
                "-",
            ),
        ],
        [
            "Languages",
            language_text,
        ],
        [
            "Files Scanned",
            str(
                repository.get(
                    "file_count",
                    "-",
                )
            ),
        ],
        [
            "Files Skipped",
            str(
                repository.get(
                    "files_skipped",
                    "-",
                )
            ),
        ],
        [
            "Compatibility Score",
            f"{score} / 100",
        ],
        [
            "Migration Complexity",
            str(migration_complexity),
        ],
    ]

    summary_table = Table(
        summary,
        colWidths=[
            2.3 * inch,
            4.7 * inch,
        ],
    )

    summary_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.HexColor("#F5F5F5"),
                ),

                (
                    "FONTNAME",
                    (0, 0),
                    (0, -1),
                    "Helvetica-Bold",
                ),

                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.grey,
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),

                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    8,
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
            ]
        )
    )

    story.append(summary_table)

    story.append(
        Spacer(
            1,
            28,
        )
    )

    # =====================================================
    # Migration Readiness
    # =====================================================

    story.append(
        Paragraph(
            "Migration Readiness",
            SECTION,
        )
    )

    left = Paragraph(
        f"""
        <para align="center">

        <font size="38">
        <b>{score}</b>
        </font>

        <br/><br/>

        <font size="14">
        Compatibility Score
        </font>

        </para>
        """,
        BODY,
    )

    right = Paragraph(
        f"""
        <b>Migration Complexity</b><br/>
        {migration_complexity}

        <br/><br/>

        <b>Estimated Engineering Effort</b><br/>
        {estimated_hours} Hours

        <br/><br/>

        <b>Risk Level</b><br/>
        {risk_level}
        """,
        BODY,
    )

    readiness = Table(
        [
            [
                left,
                right,
            ]
        ],
        colWidths=[
            2.4 * inch,
            4.6 * inch,
        ],
    )

    readiness.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, 0),
                    colors.HexColor("#C8102E"),
                ),

                (
                    "TEXTCOLOR",
                    (0, 0),
                    (0, 0),
                    colors.white,
                ),

                (
                    "BACKGROUND",
                    (1, 0),
                    (1, 0),
                    colors.HexColor("#F7F7F7"),
                ),

                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    1,
                    colors.grey,
                ),

                (
                    "LEFTPADDING",
                    (0, 0),
                    (-1, -1),
                    18,
                ),

                (
                    "RIGHTPADDING",
                    (0, 0),
                    (-1, -1),
                    18,
                ),

                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    18,
                ),

                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    18,
                ),

                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
            ]
        )
    )

    story.append(readiness)

    story.append(
        Spacer(
            1,
            28,
        )
    )

    # =====================================================
    # PART 2B STARTS HERE
    # =====================================================

        # =====================================================
    # Compatibility Summary
    # =====================================================

    components = compatibility.get(
        "components",
        [],
    )

    supported = []
    partial = []
    unsupported = []

    for component in components:

        status = (
            component.get(
                "status",
                "",
            )
            .lower()
            .strip()
        )

        name = component.get(
            "name",
            component.get(
                "component",
                "Unknown",
            ),
        )

        if status == "supported":
            supported.append(name)

        elif status == "partial":
            partial.append(name)

        else:
            unsupported.append(name)

    def status_column(
        title: str,
        header_color,
        items: list[str],
    ):

        rows = [
            [
                Paragraph(
                    f"<b>{title}</b>",
                    BODY,
                )
            ]
        ]

        if not items:

            rows.append(
                [
                    Paragraph(
                        "-",
                        BODY,
                    )
                ]
            )

        else:

            for item in items:

                rows.append(
                    [
                        Paragraph(
                            item,
                            BODY,
                        )
                    ]
                )

        table = Table(
            rows,
            colWidths=[
                2.15 * inch,
            ],
        )

        table.setStyle(
            TableStyle(
                [

                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        header_color,
                    ),

                    (
                        "TEXTCOLOR",
                        (0, 0),
                        (-1, 0),
                        colors.white,
                    ),

                    (
                        "FONTNAME",
                        (0, 0),
                        (-1, 0),
                        "Helvetica-Bold",
                    ),

                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.35,
                        colors.grey,
                    ),

                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, 0),
                        8,
                    ),

                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, 0),
                        8,
                    ),

                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "TOP",
                    ),

                ]
            )
        )

        return table

    story.append(
        Paragraph(
            "Compatibility Summary",
            SECTION,
        )
    )

    story.append(
        Paragraph(
            """
            The following table summarizes repository
            compatibility with AMD ROCm based on
            deterministic repository analysis.
            """,
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            10,
        )
    )

    compatibility_table = Table(
        [
            [

                status_column(
                    "Supported",
                    colors.HexColor("#2E7D32"),
                    supported,
                ),

                status_column(
                    "Partial",
                    colors.HexColor("#F9A825"),
                    partial,
                ),

                status_column(
                    "Unsupported",
                    colors.HexColor("#C62828"),
                    unsupported,
                ),

            ]
        ],
        colWidths=[
            2.25 * inch,
            2.25 * inch,
            2.25 * inch,
        ],
    )

    compatibility_table.setStyle(
        TableStyle(
            [
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "TOP",
                ),
            ]
        )
    )

    story.append(
        compatibility_table,
    )

    story.append(
        Spacer(
            1,
            30,
        )
    )

    hr(story)

    # =====================================================
    # PART 3 STARTS HERE
    # =====================================================

        # =====================================================
    # Executive Summary
    # =====================================================

    executive_summary = advisor.get(
        "executiveSummary",
        "",
    )

    blockers = advisor.get(
        "keyBlockers",
        [],
    )

    alternatives = advisor.get(
        "recommendedAlternatives",
        [],
    )

    migration_steps = advisor.get(
        "migrationSteps",
        [],
    )

    story.append(
        Paragraph(
            "Executive Summary",
            SECTION,
        )
    )

    if executive_summary:

        story.append(
            Paragraph(
                executive_summary,
                BODY,
            )
        )

    else:

        story.append(
            Paragraph(
                f"""
                AMD Port Studio analyzed this repository and
                calculated an overall compatibility score of
                <b>{score}</b>.

                The repository contains NVIDIA-specific
                components that should be migrated before
                production deployment on AMD ROCm.
                """,
                BODY,
            )
        )

    story.append(
        Spacer(
            1,
            18,
        )
    )

    #
    # Blockers
    #

    story.append(
        Paragraph(
            "<b>Top Migration Blockers</b>",
            BODY,
        )
    )

    if blockers:

        for blocker in blockers[:5]:

            story.append(
                Paragraph(
                    f"• {blocker}",
                    BODY,
                )
            )

    else:

        story.append(
            Paragraph(
                "No major blockers detected.",
                BODY,
            )
        )

    story.append(
        Spacer(
            1,
            16,
        )
    )

    #
    # Alternatives
    #

    story.append(
        Paragraph(
            "<b>Recommended AMD Alternatives</b>",
            BODY,
        )
    )

    if alternatives:

        for item in alternatives[:5]:

            story.append(
                Paragraph(
                    f"• {item}",
                    BODY,
                )
            )

    else:

        story.append(
            Paragraph(
                "No AMD replacements required.",
                BODY,
            )
        )

    story.append(
        Spacer(
            1,
            18,
        )
    )

    #
    # Migration Plan
    #

    story.append(
        Paragraph(
            "<b>Suggested Migration Plan</b>",
            BODY,
        )
    )

    if migration_steps:

        for index, step in enumerate(
            migration_steps,
            start=1,
        ):

            story.append(
                Paragraph(
                    f"{index}. {step}",
                    BODY,
                )
            )

    else:

        story.append(
            Paragraph(
                """
                1. Assess repository

                2. Replace CUDA dependencies

                3. Port custom kernels

                4. Validate on ROCm

                5. Benchmark

                6. Deploy
                """,
                BODY,
            )
        )

    story.append(
        Spacer(
            1,
            28,
        )
    )

    hr(story)

    # =====================================================
    # Migration Timeline
    # =====================================================

    story.append(
        Paragraph(
            "Migration Timeline",
            SECTION,
        )
    )

    story.append(
        Paragraph(
            """
            Recommended implementation order
            generated using deterministic
            analysis and AI planning.
            """,
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            10,
        )
    )

    timeline_rows = [
        [
            "Phase",
            "Activity",
            "Progress",
        ]
    ]

    if not migration_steps:

        migration_steps = [
            "Repository Assessment",
            "Environment Preparation",
            "CUDA → HIP Migration",
            "Validation & Benchmark",
            "Production Deployment",
        ]

    total_steps = len(
        migration_steps,
    )

    for index, step in enumerate(
        migration_steps,
        start=1,
    ):

        if index == 1:

            progress = "████"

        elif index == total_steps:

            progress = "████████"

        else:

            progress = "████████████"

        timeline_rows.append(
            [
                f"Phase {index}",
                step,
                progress,
            ]
        )

    timeline_table = Table(
        timeline_rows,
        colWidths=[
            1.2 * inch,
            4.5 * inch,
            1.3 * inch,
        ],
    )

    timeline_table.setStyle(
        TableStyle(
            [

                (
                    "BACKGROUND",
                    (0,0),
                    (-1,0),
                    colors.HexColor("#C8102E"),
                ),

                (
                    "TEXTCOLOR",
                    (0,0),
                    (-1,0),
                    colors.white,
                ),

                (
                    "GRID",
                    (0,0),
                    (-1,-1),
                    0.35,
                    colors.grey,
                ),

                (
                    "FONTNAME",
                    (0,0),
                    (-1,0),
                    "Helvetica-Bold",
                ),

                (
                    "BOTTOMPADDING",
                    (0,0),
                    (-1,0),
                    8,
                ),

                (
                    "TOPPADDING",
                    (0,0),
                    (-1,0),
                    8,
                ),

                (
                    "VALIGN",
                    (0,0),
                    (-1,-1),
                    "MIDDLE",
                ),

            ]
        )
    )

    story.append(
        timeline_table,
    )

    story.append(
        Spacer(
            1,
            28,
        )
    )

    hr(story)

    # =====================================================
    # PART 3B STARTS HERE
    # =====================================================

        # =====================================================
    # AI Recommendations
    # =====================================================

    story.append(
        Paragraph(
            "AI Recommendations",
            SECTION,
        )
    )

    story.append(
        Paragraph(
            """
            Prioritized migration actions generated using
            deterministic repository analysis and AI planning.
            """,
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            10,
        )
    )

    recommendation_rows: list[list[Any]] = [
    [
        Paragraph("<b>Priority</b>", BODY),
        Paragraph("<b>Recommendation</b>", BODY),
        Paragraph("<b>Impact</b>", BODY),
    ]
]

    if not recommendations:

        recommendations = [
            "Replace NVIDIA Docker base image with ROCm image.",
            "Install ROCm-enabled PyTorch.",
            "Port CUDA kernels using HIP.",
        ]

    for index, item in enumerate(recommendations):

      if isinstance(item, dict):

        recommendation = (
            item.get("action")
            or item.get("recommendation")
            or item.get("title")
            or item.get("text")
            or "Recommendation"
        )

        rationale = item.get("rationale")

        if rationale:
            recommendation += (
                "<br/><font size='8' color='grey'>"
                + rationale
                + "</font>"
            )

        priority = str(
            item.get("priority", "Medium")
        ).title()

        impact = str(
            item.get("impact", priority)
        ).title()

      else:

        recommendation = str(item)

        if index == 0:
            priority = "High"
            impact = "High"

        elif index == 1:
            priority = "Medium"
            impact = "Medium"

        else:
            priority = "Low"
            impact = "Low"

      recommendation_rows.append(
        [
            Paragraph(priority, BODY),
            Paragraph(recommendation, BODY),
            Paragraph(impact, BODY),
        ]
    )

    recommendation_table = Table(
        recommendation_rows,
        colWidths=[
            1.0 * inch,
            5.5 * inch,
            0.8 * inch,
        ],
        repeatRows=1,
    )

    recommendation_table.setStyle(
        TableStyle(
            [

                (
                    "BACKGROUND",
                    (0,0),
                    (-1,0),
                    colors.HexColor("#C8102E"),
                ),

                (
                    "TEXTCOLOR",
                    (0,0),
                    (-1,0),
                    colors.white,
                ),

                (
                    "GRID",
                    (0,0),
                    (-1,-1),
                    0.35,
                    colors.grey,
                ),

                (
                    "FONTNAME",
                    (0,0),
                    (-1,0),
                    "Helvetica-Bold",
                ),

                (
                    "BOTTOMPADDING",
                    (0,0),
                    (-1,0),
                    8,
                ),

                (
                    "TOPPADDING",
                    (0,0),
                    (-1,0),
                    8,
                ),

                (
                    "VALIGN",
                    (0,0),
                    (-1,-1),
                    "TOP",
                ),
                
                (
                  "LEFTPADDING",
                  (0, 0),
                  (-1, -1),
                  8,
              ),

              (
                  "RIGHTPADDING",
                  (0, 0),
                  (-1, -1),
                  8,
              ),
            ]
        )
    )

    story.append(
        recommendation_table,
    )

    story.append(
        Spacer(
            1,
            28,
        )
    )

    hr(story)

    # =====================================================
    # Confidence Summary
    # =====================================================

    story.append(
        Paragraph(
            "Confidence Summary",
            SECTION,
        )
    )

    story.append(
        Paragraph(
            """
            Confidence indicates the reliability of each
            analysis component based on deterministic
            scanning and AI validation.
            """,
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            10,
        )
    )

    confidence_rows = [
        [
            "Analysis Area",
            "Confidence",
            "Reason",
        ]
    ]

    preferred_order = [
        "cuda",
        "dependencies",
        "docker",
        "compatibility",
        "recommendations",
        "aiSummary",
        "overall",
    ]

    for key in preferred_order:

        value = confidence.get(key)

        if not isinstance(value, dict):
            continue

        confidence_rows.append(
            [
                key.replace("_", " ").title(),
                str(
                    value.get(
                        "score",
                        "-",
                    )
                ),
                value.get(
                    "reason",
                    "-",
                ),
            ]
        )

    if len(confidence_rows) == 1:

        confidence_rows.append(
            [
                "Overall",
                "High",
                "Analysis completed successfully.",
            ]
        )

    confidence_table = Table(
        confidence_rows,
        colWidths=[
            2.1 * inch,
            1.1 * inch,
            3.9 * inch,
        ],
    )

    confidence_table.setStyle(
        TableStyle(
            [

                (
                    "BACKGROUND",
                    (0,0),
                    (-1,0),
                    colors.HexColor("#C8102E"),
                ),

                (
                    "TEXTCOLOR",
                    (0,0),
                    (-1,0),
                    colors.white,
                ),

                (
                    "GRID",
                    (0,0),
                    (-1,-1),
                    0.35,
                    colors.grey,
                ),

                (
                    "FONTNAME",
                    (0,0),
                    (-1,0),
                    "Helvetica-Bold",
                ),

                (
                    "BOTTOMPADDING",
                    (0,0),
                    (-1,0),
                    8,
                ),

                (
                    "TOPPADDING",
                    (0,0),
                    (-1,0),
                    8,
                ),

                (
                    "VALIGN",
                    (0,0),
                    (-1,-1),
                    "TOP",
                ),

            ]
        )
    )

    story.append(
        confidence_table,
    )

    story.append(
        Spacer(
            1,
            32,
        )
    )

    hr(story)

    # =====================================================
    # PART 4 STARTS HERE
    # =====================================================

        # =====================================================
    # End of Report
    # =====================================================

    story.append(
        Paragraph(
            "End of Report",
            SECTION,
        )
    )

    story.append(
        Paragraph(
            """
            Thank you for using <b>AMD Port Studio</b>.

            This assessment combines deterministic repository
            analysis, dependency graph generation,
            compatibility evaluation,
            AI-assisted migration planning,
            and ROCm best-practice recommendations.

            The report is intended to accelerate
            NVIDIA CUDA → AMD ROCm migration planning
            while reducing engineering effort and migration risk.
            """,
            BODY,
        )
    )

    story.append(
        Spacer(
            1,
            30,
        )
    )

    story.append(
        Paragraph(
            "<b>Generated Artifacts</b>",
            BODY,
        )
    )

    artifacts = [
        "✓ Repository Scan",
        "✓ Dependency Graph",
        "✓ Compatibility Analysis",
        "✓ AI Migration Planner",
        "✓ Docker Migration Guide",
        "✓ ROCm Recommendations",
        "✓ Migration Timeline",
        "✓ Confidence Assessment",
    ]

    for artifact in artifacts:

        story.append(
            Paragraph(
                artifact,
                BODY,
            )
        )

    story.append(
        Spacer(
            1,
            30,
        )
    )

    hr(story)

    story.append(
        Paragraph(
            """
            <font color="#777777">

            AMD Port Studio

            AI-powered migration assistant for
            accelerating NVIDIA CUDA workloads
            to AMD ROCm.

            </font>
            """,
            SMALL,
        )
    )

    # =====================================================
    # Build PDF
    # =====================================================

    doc.build(
        story,
        onFirstPage=page_template,
        onLaterPages=page_template,
    )

    buffer.seek(0)

    return buffer